#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"


_emit_defines()
{
   while [ "$#" -ne 0 ]
   do
      case "$1" in
         -D)
            shift
            echo "$1"
         ;;

         -D*)
            cut -c3- <<< "${1}"
         ;;

         -N|-L*)
         ;;

         -[A-V])
            shift
         ;;
      esac

      shift
   done
}


emit_defines()
{
   local escaped_test_path
   local escaped_tmp_path

   escaped_test_path="`escaped_sed_pattern "${MULLE_TEST_DIR}"`"
   escaped_tmp_path="`escaped_sed_pattern "${MULLE_TMP_DIR}"`"
   _emit_defines "$@"| sed -e "s/${escaped_test_path:-^}//" -e "s/${escaped_tmp_path:-^}//"
}


main()
{
   local envvar
   local filename

   envvar="`basename -- "$0" | sed 's/^[A-Za-z]*-\(.*\)/\1/' | tr '[a-z]' '[A-Z|'`_REDIRECT_FILE"
   filename="`eval echo "\\\$$envvar"`"

   if [ ! -z "${filename}"  ]
   then
      log_info "${MULLE_EXECUTABLE_NAME}: Writing defines to \"${filename}\""
      emit_defines "$@" | LC_ALL=C sort > "${filename}"
   else
      emit_defines "$@" | LC_ALL=C sort
   fi
}


init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`"

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" "minimal" || exit 1
}


init "$@"
main "$@"
