#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"


###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions-minimal.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###


filter_darwin()
{
   sed -e 's|/Applications/Xcode.*\.app/.*/MacOSX.*\.sdk|\${SDKPATH}|g' |
   sed -e 's|/Library/Developer/CommandLineTools/SDKs/MacOSX.*\.sdk|\${SDKPATH}|g'
}


_emit_defines()
{
   while [ "$#" -ne 0 ]
   do
      case "$1" in
         -D)
            shift
            printf "%s\n" "$1"
         ;;

         -D*)
            cut -c3- <<< "${1}"
         ;;

         -N|-L*)
         ;;

         --*-dir|--configuration|--sdk)
            printf "%s %s\n" "$1" "$2"
            shift
         ;;
      esac

      shift
   done
}


emit_defines()
{
   local escaped_test_path
   local escaped_tmp_path

   [ -z "${MULLE_TEST_DIR}" ] && _internal_fail "MULLE_TEST_DIR is undefined"
   [ -z "${MULLE_TMP_DIR}" ] && _internal_fail "MULLE_TMP_DIR is undefined"

   r_escaped_sed_pattern "${MULLE_TEST_DIR}"
   escaped_test_path="${RVAL}"
   r_escaped_sed_pattern "${MULLE_TMP_DIR}"
   escaped_tmp_path="${RVAL}"
   _emit_defines "$@"| sed -e "s/${escaped_test_path:-^}/\${MULLE_TEST_DIR}/g" -e "s/${escaped_tmp_path:-^}/\${MULLE_TMP_DIR}/g"
}


main()
{
   local envvar
   local filename

   # remove mock- prefix , convert to uppercase, append _REDIRECT_FILE
   envvar="`basename -- "$0" | sed 's/^mock-\(.*\)/\1/' | tr '[:lower:]-' '[:upper:]_'`_REDIRECT_FILE"

   if [ ${ZSH_VERSION+x} ]
   then
      filename="${(P)envvar}"
   else
      filename="${!envvar}"
   fi

   if [ ! -z "${filename}"  ]
   then
      log_info "${MULLE_EXECUTABLE_NAME}: Writing defines to \"${filename}\""
      emit_defines "$@" | filter_darwin | LC_ALL=C sort > "${filename}"
   else
      emit_defines "$@" | filter_darwin | LC_ALL=C sort
   fi
}


main "$@"
