#! /bin/sh
#
#   Copyright (c) 2016 Nat! - Mulle kybernetiK
#   Copyright (c) 2016 Nat! - Codeon GmbH
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.

MULLE_INSTALL_VERSION="0.3"

MULLE_BOOTSTRAP_MIN_MAJOR="2"
MULLE_BOOTSTRAP_MIN_MINOR="1"


PATH="`pwd -P`/addictions/bin:$HOME/.linuxbrew/bin:/usr/local/bin:${HOME}/bin:${PATH}"


usage()
{
   cat <<EOF >&2
usage:
   ${executable} [options] [url|clean]

   Options:
      -b <tag|branch> : specify tag or branch to fetch from URL
      -d              : build debug
      -f              : don't build dependencies with mulle-bootstrap
                        Embedded_repositories will be fetched though.
      -m <executable> : specify make program to use
      -p <prefix>     : install prefix (default: ${DEFAULT_INSTALL})
      -s <scm>        : specify an SCM other than git (e.g. svn)

   Arguments:
      clean           : clean project
      url             : URL to clone, build and install.
                        If no URL is specified, ${executable} will use "local
                        mode". The current directory is assumed to be the
                        project directory.
                        "Local mode" is limited to cmake projects.
EOF
   exit 1
}


#
# URL Mode
#
do_clone_magic()
{
   local url
   local scm
   local tag
   local prefix

   url="$1"
   [ $# -ne 0 ] && shift
   tag="$1"
   [ $# -ne 0 ] && shift
   scm="$1"
   [ $# -ne 0 ] && shift
   prefix="$1"
   [ $# -ne 0 ] && shift
   debug="$1"
   [ $# -ne 0 ] && shift


   [ -z "${url}" ] && fail "URL is empty"

   #
   # if url is local directory, make relative absolute
   #
   case "${url}" in
      /*|*:/*)
      ;;

      *)
         if [ -d "${url}" ]
         then
            url="`pwd -P`/${url}"
         fi
      ;;
   esac

   local random
   local debugoptions

   if [ ! -z "${debug}" ]
   then
      debugoptions="--configuration Debug"
   fi

   local command

   random=`exekutor mktemp -d -t "mulle-install.XXXX"`

   (
      exekutor cd "${random}"|| exit 1 ;
      exekutor mulle-bootstrap init -n ;
      exekutor echo "$url;;$tag;$scm" > .bootstrap/repositories
      exekutor mulle-bootstrap  ${BOOTSTRAP_FLAGS} -a bootstrap ${debugoptions} "$@" || exit 1

      if [ -z "${DONT_INSTALL}" ]
      then
         if [ -z "${prefix}" ]
         then
            exekutor mulle-bootstrap install || exit 1
         else
            exekutor mulle-bootstrap install "${prefix}" || exit 1
         fi
      fi
   )
   if [ -z "${DONT_REMOVE}" ]
   then
      exekutor chmod -R ugo+w "${random}"
      exekutor rm -rf "${random}"
   else
      log_info "Build in \"${random}\""
   fi
}


#
# Local Mode
#
do_fetch_dependencies()
{
   if refresh_needed
   then
      exekutor mulle-bootstrap refresh || exit 1
   fi

   if fetch_needed
   then
      exekutor mulle-bootstrap -fr ${BOOTSTRAP_FLAGS} fetch || exit 1 # --embedded-only
      #
      # after the first fetch don't warn about scripts again
      #
      if [ "`basename "$executable"`" = "mulle-build" ]
      then
         log_verbose "Don't warn about scripts next build"
         mulle-bootstrap config --on dont_warn_scripts
      fi
   fi
}


do_build_dependencies()
{
   if build_needed
   then
      if [ -z "${FETCH_ONLY}" ]
      then
         exekutor mulle-bootstrap ${BOOTSTRAP_FLAGS} build || exit 1
      fi
   fi
}


do_install_dependencies()
{
   if [ "${OPTIMISTIC}" = "YES" ]
   then
      return
   fi

   if [ -z "${DONT_INSTALL}" -a -z "${FETCH_ONLY}" ]
   then
      exekutor mulle-bootstrap install "${CMAKE_INSTALL_PREFIX}" || exit 1
   fi
}


cmake_clean()
{
   log_verbose "Deleting build/CMakeFiles"
   exekutor rm -rf build/CMakeFiles 2> /dev/null

   log_verbose "Deleting build/CMakeCache.txt"
   exekutor rm build/CMakeCache.txt 2> /dev/null
}


need_cmake_clean()
{
   if [ ! -f "${BUILDDIR}/CMakeFiles" ]
   then
      return 0
   fi

   if [ .CC -nt "${BUILDDIR}/CMakeFiles" ]
   then
      return 0
   fi

   if [ .CXX -nt "${BUILDDIR}/CMakeFiles" ]
   then
      return 0
   fi

   return 1
}


need_cmake_build()
{
   if [ ! -f "${BUILDDIR}/CMakeFiles" ]
   then
      return 0
   fi

   if [ CMakeFiles.txt -nt "${BUILDDIR}/CMakeFiles.txt" ]
   then
      return 0
   fi

   return 1
}


_do_build()
{
   local debugoptions

   if [ ! -z "${debug}" ]
   then
      debugoptions="-DCMAKE_BUILD_TYPE=Debug"
   fi

   local relative

   case "${BUILDDIR}" in
      */*)
        relative="`perfect_relative_path_between "${PWD}" "${BUILDDIR}"`"
      ;;

      *)
         relative=".."
      ;;
   esac

   #
   # Figure out C/CXX compiler (only for current) project
   #
   local  cc

   cc="`cat .CC 2> /dev/null`"
   if [ ! -z "${cc}" ]
   then
      log_verbose "Compiler ${C_RESET_BOLD}CC${C_VERBOSE} set to ${C_MAGENTA}${C_BOLD}${cc}${C_VERBOSE} found in \".CC\""
      CMAKE_FLAGS="`concat "${CMAKE_FLAGS}" "-DCMAKE_C_COMPILER=${cc}"`"
   fi

   local  cxx

   cxx="`cat .CXX 2> /dev/null`"
   if [ ! -z "${cxx}" ]
   then
      log_verbose "Compiler ${C_RESET_BOLD}CXX${C_VERBOSE} set to ${C_MAGENTA}${C_BOLD}${cxx}${C_VERBOSE} found in \".CXX\""
      CMAKE_FLAGS="`concat "${CMAKE_FLAGS}" "-DCMAKE_CXX_COMPILER=${cxx}"`"
   fi

   mkdir "${BUILDDIR}" 2> /dev/null
   (
      # CMAKE_FLAGS same as in mulle-bootstrap
      exekutor cd "${BUILDDIR}" ;
      exekutor cmake -DCMAKE_INSTALL_PREFIX="${CMAKE_INSTALL_PREFIX}" \
                     -G "${CMAKE_GENERATOR}" \
                     ${debugoptions} \
                     ${CMAKE_FLAGS} \
                     "$@" \
                     "${relative}" || exit 1
   )
}


do_build()
{
   local skip_build

   skip_build="${OPTIMISTIC}"

   if need_cmake_clean
   then
      cmake_clean
      skip_build="NO"
   fi


   if [ skip_build = "NO" ] || need_cmake_build
   then
      _do_build "$@"
   fi
}


#
# if we are using brew the dependencies are also installed via
# brew, otherwise install dependencies too
#
do_install()
{
   local command

   if [ -z "${DONT_INSTALL}" ]
   then
      command="install"
   fi

   (
      exekutor cd build ;
      exekutor "${MAKE}" ${MAKE_FLAGS} ${command} || exit 1 ;
   )
}


#
#
#
setup_make_environment()
{
   if [ -z "${MAKE}" ]
   then
      case "`uname`" in
         MINGW*)
            MAKE="nmake"
         ;;

         *)
            MAKE="make"
         ;;
      esac
   fi

   if [ -z "${CMAKE_GENERATOR}" ]
   then
      case "${MAKE}" in
         nmake*)
            CMAKE_GENERATOR="NMake Makefiles"
         ;;

         *)
            CMAKE_GENERATOR="Unix Makefiles"
         ;;
      esac
   fi
}


check_mulle_bootstrap_version()
{
   local version
   local major
   local minor

   version="`mulle-bootstrap version | head -1`"
   [ -z "${version}" ] && fail "mulle-bootstrap did not provide a version"

   major="`echo "${version}" | cut -s -d. -f1`"
   if [ "${major}" -gt "${MULLE_BOOTSTRAP_MIN_MAJOR}" ]
   then
      return 1
   fi

   if [ "${major}" -eq "${MULLE_BOOTSTRAP_MIN_MAJOR}" ]
   then
      minor="`echo "${version}" | cut -s -d. -f2`"
      if [ "${minor}" -lt "${MULLE_BOOTSTRAP_MIN_MINOR}" ]
      then
         return 1
      fi
   fi

   return 0
}


setup_bootstrap_environment()
{
   local libexec

   libexec="`mulle-bootstrap library-path 2> /dev/null | head -1`"
   if [ -z "${libexec}" ]
   then
      echo "mulle-bootstrap not installed or not in PATH" >&2
      exit 1
   fi

   PATH="${libexec}:$PATH"

   . mulle-bootstrap-logging.sh
   . mulle-bootstrap-functions.sh
   . mulle-bootstrap-local-environment.sh

   if check_mulle_bootstrap_version
   then
      return
   fi

   fail "$executable: mulle-bootstrap needs to be updated."
}


git_pull()
{
   local branch
   local origin

   log_fluff ":.:pull:.:"

   branch="`git rev-parse --abbrev-ref HEAD`"
   if [ -d ".git/refs/remotes/origin" ]
   then
      origin="${ORIGIN:-origin}"
   else
      origin="`git remote | head -1`"
   fi

   if [ ! -z "${origin}" ]
   then
      git pull "${origin}" "${branch}"  # or what ?
   fi
}


local_clean()
{
   log_fluff ":.:clean:.:"

   local cleandefault

   if [ $# -eq 0 ]
   then
      if [ -z "${DONT_INSTALL}" ]
      then
         cleandefault=dist    # mulle-install clean
      else
         cleandefault=output  # mulle-build clean
      fi
   else
      case "$1" in
         cmake)
            cmake_clean
            return
         ;;
      esac
   fi
}


local_mode()
{
   log_fluff ":.:local mode:.:"

   setup_make_environment

   [ -z "${TAG}" ]        || fail "$executable: -b option is not compatible with local mode."
   [ -z "${SCM}" ]        || fail "$executable: -s option is not compatible with local mode."

   if [ -d .bootstrap ]
   then
      do_fetch_dependencies
      if [ -z "${FETCH_ONLY}" ]
      then
         do_build_dependencies
      fi
   else
      log_fluff "No .bootstrap found, so not bootstrapping"
   fi

   [ ! -f CMakeLists.txt ] && fail "$executable: Can only build cmake based projects, in local mode."
   do_build "$@"

   if [ -d .bootstrap ]
   then
      do_install_dependencies
   fi

   do_install
}


url_mode()
{
   log_fluff ":.:URL mode:.:"

   [ -z "${FETCH_ONLY}" ] || fail "$executable: -nb option is not compatible with URL install."
   [ -z "${MAKE}" ]       || fail "$executable: -m option is not compatible with URL install."

   do_clone_magic "${URL}" "${TAG}" "${SCM}" "${CMAKE_INSTALL_PREFIX}" "${DEBUG}" "$@"
}


main()
{
   local executable
   local command

   #
   # allow variations, mulle-build, mulle-install mulle-clean
   # mulle-tag etc
   #
   executable=`basename "$0"`
   command="`echo "${executable}" | cut -d- -f2`"

   setup_bootstrap_environment

   BOOTSTRAP_FLAGS=
   BUILDDIR="${BUILDDIR:-build}"
   OPTIMISTIC="${OPTIMISITIC:-YES}"

   if [ "${executable}" = "mulle-build" ]
   then
      DONT_INSTALL="YES"
   fi

   case "`uname`" in
      MINGW*)
         DEFAULT_INSTALL="~"
      ;;

      *)
         DEFAULT_INSTALL="/usr/local"
      ;;
   esac

   while [ $# -ne 0 ]
   do
      case "$1" in
         -b|--tag|--branch)
            shift
            [ $# -eq 0 ] && usage

            TAG="$1"
         ;;

         -d|--debug)
            DEBUG="YES"
         ;;

         -ni|--no-install)
            DONT_INSTALL="YES"
         ;;

         -nb|--no-build|--brew)  # brew is historic :)
            # enable &usr/local/include check
            BOOTSTRAP_FLAGS="`concat "${BOOTSTRAP_FLAGS}" "-c"`"
            FETCH_ONLY="YES"
         ;;

         -nr|--no-remove)
            DONT_REMOVE="YES"
         ;;

         -u|--pessimistic|--unlucky)
            OPTIMISTIC="NO"
         ;;

         -m|--make)
            shift
            [ $# -eq 0 ] && usage

            MAKE="$1"
         ;;

         -p|--prefix)
            shift
            [ $# -eq 0 ] && usage

            CMAKE_INSTALL_PREFIX="$1"
         ;;

         -s|--scm)
            shift
            [ $# -eq 0 ] && usage

            SCM="$1"
         ;;

         -n|--dry-run)
            BOOTSTRAP_FLAGS="`concat "${BOOTSTRAP_FLAGS}" "$1"`"
            MULLE_EXECUTOR_DRY_RUN="YES"
         ;;

         -te|--trace-execution)
            BOOTSTRAP_FLAGS="`concat "${BOOTSTRAP_FLAGS}" "$1"`"
            MULLE_EXECUTOR_TRACE="YES"
         ;;

         -t|--trace)
            BOOTSTRAP_FLAGS="`concat "${BOOTSTRAP_FLAGS}" "$1"`"
            set -x
         ;;

         -v|--verbose)
            BOOTSTRAP_FLAGS="`concat "${BOOTSTRAP_FLAGS}" "$1"`"
            MULLE_BOOTSTRAP_FLUFF="NO"
            MULLE_BOOTSTRAP_VERBOSE="YES"
         ;;

         -vv|--very-verbose)
            BOOTSTRAP_FLAGS="`concat "${BOOTSTRAP_FLAGS}" "$1"`"
            MULLE_BOOTSTRAP_FLUFF="YES"
            MULLE_BOOTSTRAP_VERBOSE="YES"
         ;;

         -vvv|--very-verbose-with-settings)
            BOOTSTRAP_FLAGS="`concat "${BOOTSTRAP_FLAGS}" "$1"`"
            MULLE_BOOTSTRAP_FLUFF="YES"
            MULLE_BOOTSTRAP_VERBOSE="YES"
            MULLE_EXECUTOR_TRACE="YES"
         ;;

         --version)
            echo "${MULLE_INSTALL_VERSION}"
            exit 0
         ;;

         -h|--help)
            usage
         ;;

         -*)
            BOOTSTRAP_FLAGS="`concat "${BOOTSTRAP_FLAGS}" "$1"`"
         ;;

         *)
            break
         ;;
      esac

      shift
   done


   if [ "${OPTIMISTIC}" = "YES" ]
   then
      BOOTSTRAP_FLAGS="`concat "${BOOTSTRAP_FLAGS}" "-l"`"
   fi

   #
   # allow mulle-build clean and others..
   #
   if [ "${command}" = "build" ]
   then
      case "$1" in
         test|install|build|update|pull|tag|clean|refresh|setup-xcode|xcode|library-path|init|fetch|dist|config|bootstrap|nomagic)
            command="$1"
            shift
         ;;
      esac
   fi

   case "${command}" in
      install|build)
         URL="$1"

         case "${URL}" in
            "")
               local_mode "$@"
            ;;

            */*|*:*)
               url_mode "$@"
            ;;
         esac
      ;;

      update|pull)
         mulle-bootstrap ${BOOTSTRAP_FLAGS} "${command}" "$@" || exit 1
         if [ -d .git ]
         then
            git_pull
         fi
      ;;

      tag)
         mulle-bootstrap ${BOOTSTRAP_FLAGS} "${command}" "$@" || exit 1
         git tag "$@" || exit 1
      ;;

      clean)
         mulle-bootstrap ${BOOTSTRAP_FLAGS} clean "$@" ${cleandefault}
         local_clean "$@"
      ;;

      test)
         testdir="${TESTS:-tests}"
         if [ -x "${testdir}/build-test.sh" ]
         then
             ( exekutor cd "${testdir}" ; exekutor "./build-test.sh" "$@" ) || exit 1
         fi

         if [ -x "${testdir}/run-test.sh" ]
         then
            ( exekutor cd "${testdir}" ; exekutor "./run-test.sh" "$@" ) || exit 1
         else
            fail "Don't know how to run tests (${testdir}/run-test.sh is missing)"
         fi
      ;;

      # catches all paths and URLS, abolute, relative

      # other commands forward to mulle-bootstrap
      *)
         mulle-bootstrap ${BOOTSTRAP_FLAGS} "${command}" "$@" || exit 1
      ;;

   esac
}


main "$@"
