#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"


run_mulle_craft()
{
   log_fluff "####################################"
   log_fluff ${MULLE_CRAFT} ${MULLE_CRAFT_FLAGS} "$@"
   log_fluff "####################################"

   exekutor "${MULLE_CRAFT}" ${MULLE_CRAFT_FLAGS} "$@"
}


expect_content()
{
   local output="$1"
   local expect="$2"

   if [ ! -f "${output}" ]
   then
      if [ -z "${expect}" ]
      then
         return
      fi
      fail "Did not produce \"${output}\" as expected"
   else
      if [ -z "${expect}" ]
      then
         fail "Did produce \"${output}\" unexpectedly. Nothing was expected"
      fi
   fi

   if [ -f "${expect}.${MULLE_UNAME}" ]
   then
      expect="${expect}.${MULLE_UNAME}"
   fi

   if [ ! -f "${expect}" ]
   then
      internal_fail "\"${expect}\" is missing from test"
   fi

   local diffs

   diffs="`diff -b "${output}" "${expect}"`"
   if [ $? -ne 0 ]
   then
      # fix for mingw
      if [ `wc -l <<< "${diffs}"` -eq 2 ]
      then
         if egrep -q 'CMAKE_LINKER:PATH=' <<< "${diffs}"
         then
            return 0
         fi
      fi

      if [ "${MULLE_UNAME}" = darwin ]
      then
         if [ -z "`egrep -v -e '-isysroot' <<< "${diffs}"`" ]
         then
            return 0
         fi
      fi

      log_error "Unexpected output generated"
      cat <<EOF >&2
----------------
Output: ($output)
----------------
`cat "${output}"`
----------------
Expected: ($expect)
----------------
`cat "${expect}"`
----------------
Diff:
----------------
${diffs}
----------------
EOF
      exit 1
   fi
}


run_test()
{
   local directory="$1" ; shift
   local expect="$1"; shift

   MULLE_MAKE_REDIRECT_FILE="${directory}/mulle-make-args.txt"
   export MULLE_MAKE_REDIRECT_FILE

   MULLE_TMP_DIR="${directory}" \
   MULLE_TEST_DIR="${PWD}" \
   MULLE_MAKE="${PWD}/../mock-mulle-make" \
   ADDICTION_DIR="${directory}/addiction" \
   DEPENDENCY_DIR="${directory}/dependency" \
   BUILD_DIR="${directory}/build" \
      run_mulle_craft "$@"

   if [ $? -ne 0 ]
   then
      exit 1
   fi

   expect_content "${MULLE_MAKE_REDIRECT_FILE}" "${expect}"
   remove_file_if_present "${MULLE_MAKE_REDIRECT_FILE}"
   rmdir_safer "${directory}/build"
}


main()
{
   MULLE_CRAFT_FLAGS="$@"

   _options_mini_main "$@"

   local directory

   directory="`make_tmp_directory`"
   directory="${directory:-/tmp/test}"

   #
   # Check that some simple pass through stuff works
   #
   run_test "${directory}" "mulle-make.txt" project --debug
   log_verbose "----- #1 PASSED -----"

   run_test "${directory}" "mulle-make2.txt" --craftorder-file "${PWD}/craftorder" \
                                                craftorder --sdk foo --release
   log_verbose "----- #2 PASSED -----"

   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"
}



init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_CRAFT="${MULLE_CRAFT:-${PWD}/../../mulle-craft}"
}



init "$@"
main "$@"

